### ISSUE TITLE
Addons

### ISSUE THREAD

**Issue by vickjoeobi** [OfficialTuringDev/Mini_Ecommerce#1]
I love the neatness of the code and the implementation of various aspects of pythons. However, take note of the following: 

1. After Listing your inventory, the user gets confused on how to proceed or how to choose what to buy. 
`Welcome to the Web Store
Here is what we have in stock
('Cup Cake', 500)
('Coke', 200)
('Bread', 300)
('Milk', 250)
('Chocolate', 150)
Type the number of what you want to buy:`
please consider the user while building and testing. 

2. Please try and make the corrections so I could purchase an item and evaluate finally.

**Comment by ndcharles** [comment]
Amended the entrance section using labels and statements.

**Comment by vickjoeobi** [comment]
Weldone, I think you have done justice to the code. You can proceed to tell me your availabilities, so we can fix a meeting and discuss what's next. 

Let's make the meeting possibly this week so we can always consolidate our learnings.

**Comment by ndcharles** [comment]
Friday 9 to 4pm is fine for me. Or Saturday
